/**
 * <h1>389. Find the Difference</h1>
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * <p>
 * Example: Input: s = "abcd", t = "abcde". Output: e
 * <p>
 * Explanation: 'e' is the letter that was added.
 *
 * @author Jerry
 * @since 3/6/17
 */
public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        int[] count = new int[26];
        for (char c : s.toCharArray()) {
            count[c - 'a']++;
        }
        for (char c : t.toCharArray()) {
            if (--count[c - 'a'] < 0) {
                return c;
            }
        }
        return 0;
    }
}
